student=[]
a=int(input("Enter marks of student 1:"))
student.append(a)
b=int(input("Enter marks of student 2:"))
student.append(b)
c=int(input("Enter marks of student 3:"))
student.append(c)
d=int(input("Enter marks of student 4:"))
student.append(d)
e=int(input("Enter marks of student 5:"))
student.append(e)
f=int(input("Enter marks of student 6:"))
student.append(f)
student.sort() 
print(student)
